FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

RUN apt-get update && apt-get install -y \
    git \
    python3-dev \
    python3-pip \
    wget

# Upgrade pip
RUN pip3 install --upgrade pip

# Install Detectron2
RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git'

# Install Detic
# NOTE: Need to add `"default-runtime": "nvidia"` to `/etc/docker/daemon.json` for building custom ops.
RUN git clone https://github.com/facebookresearch/Detic.git --recurse-submodules && \
    cd Detic && \
    pip3 install -r requirements.txt && \
    cd third_party/Deformable-DETR/models/ops && \
    python3 setup.py build install

# Install pyrealsense2
RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libglfw3-dev \
    libglu1-mesa-dev \
    libgtk-3-dev \
    libssl-dev \
    libudev-dev \
    libusb-1.0-0-dev \
    pkg-config \
    python-dev \
 && rm -rf /var/lib/apt/lists/*
RUN git clone -b v2.53.1 --depth 1 https://github.com/IntelRealSense/librealsense.git && \
    cd librealsense && \
    mkdir build && cd build && \
    cmake .. \
    -DBUILD_EXAMPLES=false \
    -DCMAKE_BUILD_TYPE=release \
    -DFORCE_RSUSB_BACKEND=false \
    -DBUILD_WITH_CUDA=true \
    -DBUILD_PYTHON_BINDINGS:bool=true \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.8 \
    -DPYTHON_INSTALL_DIR=/usr/local/lib/python3.8/site-packages && \
    make -j$(($(nproc)-1)) && \
    make install

# Create non-root user
ARG USERNAME=appuser
ARG USER_UID=1000
ARG USER_GID=1000
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID --groups video -m $USERNAME
USER $USERNAME
WORKDIR /home/$USERNAME
ENV PATH $PATH:/home/appuser/.local/bin
